# FightCityTickets SwiftLint Configuration
# ==========================================

# ============================================
# Disabled Rules
# ============================================
disabled_rules:
  - trailing_whitespace
  - file_length
  - type_body_length

# ============================================
# Opt-in Rules (Enabled)
# ==========================================
opt_in_rules:
  # Style
  - closure_spacing
  - empty_count
  - explicit_init
  - force_unwrapping
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  
  # Best Practices
  - array_init
  - attributes
  - collective_closure
  - convenience_type
  - discouraged_object_literal
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - for_where
  - identical_operands
  - last_where
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - nimble_operator
  - nslocalizedstring_key
  - optional_enum_case_matching
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - strict_fileprivate
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - unused_declaration
  - unused_import
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - weak_delegate

# ============================================
# Excluded Paths
# ============================================
excluded:
  - ${PWD}/DerivedData
  - ${PWD}/.build
  - ${PWD}/Pods
  - ${PWD}/Tests/UITests
  - ${PWD}/Tests/UnitTests/iOSTests/Mocks
  - ${PWD}/Tests/UnitTests/FoundationTests/Mocks

# ============================================
# Rule Configurations
# ============================================

# Line Length
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Function Body Length
function_body_length:
  warning: 50
  error: 100
  ignore_single_line_functions: true

# Type Body Length
type_body_length:
  warning: 300
  error: 500

# File Length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Cyclomatic Complexity
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_statements: ["guard"]

# Identifier Name
identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - ok
    - no
    - x
    - y
    - z
    - i
    - j
    - k
    - e   # error
    - u   # url

# Type Name
type_name:
  min_length: 3
  max_length: 60
  excluded:
    - ID

# ============================================
# Custom Configuration by File Type
# ============================================

# Test files - more lenient
test_case_inlineable_class: true

# ============================================
# Swift Package Manager Support
# ============================================
reporter: "xcode"

# ============================================
# Custom Rules
# ============================================

custom_rules:
  # Ensure async functions are marked with async
  async_function_naming:
    name: "Async function naming"
    regex: 'func\s+\w+\s*\([^)]*\)\s*(?!async\s*\()throws?\s*->\s*(?:Void|())'
    message: "Async functions should be marked with 'async'"
    severity: error
    
  # Prefer @Published over willSet/didSet for properties
  published_property:
    name: "Use @Published for observable properties"
    regex: '(@Published\s+)?var\s+\w+:\s+\w+\s*\{(\s*willSet|get|set|\s*)\}'
    message: "Use @Published property wrapper instead of willSet/didSet"
    severity: warning
    
  # Ensure accessibility identifiers are set
  accessibility_identifier:
    name: "Accessibility identifier for UI elements"
    regex: '@State\s+private\s+var\s+.*Id:\s*String'
    message: "Consider adding an accessibilityIdentifier for UI testing"
    severity: warning
    
  # Prefer SwiftUI views to be internal or public
  view_modifier_order:
    name: "View modifier ordering"
    regex: '\.frame\(|\.padding\(|\.foregroundColor\(|\.background\(|\.cornerRadius\(|\.shadow\('
    message: "Consider grouping related modifiers together"
    severity: warning

# ============================================
# Legacy Swift (Swift 4) Support
# ============================================
legacy_hashing: error
legacy_objc_type: error
legacy_random: error

# ============================================
# Documentation Rules
# ============================================
private_declaration:
  severity: warning

# ============================================
# Performance Rules
# ============================================
reduce_into: error
yields: error
